import {initializeApp} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import {getFirestore,collection,getDocs,doc,getDoc,setDoc,updateDoc,query,orderBy} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
const cfg={apiKey:"AIzaSyC69Kn1QWhUhpGiAqMYs1o6Vrl4pgq10OA",authDomain:"victori4-fc.firebaseapp.com",projectId:"victori4-fc",storageBucket:"victori4-fc.firebasestorage.app",messagingSenderId:"337858940725",appId:"1:337858940725:web:4da5b6d8b841fd64d5467c",measurementId:"G-57SN4JXD8Z"};
const app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const POS6=['GK','DEF','MID','ATT'];
const POS11=['GK','RB','CB','LB','RWB','LWB','CDM','CM','CAM','RM','LM','RW','LW','ST','CF','SS'];
const POSLABEL=['GK — Goalkeeper','DEF — Defender','MID — Midfielder','ATT — Attacker/Forward','RB — Right Back','CB — Centre Back','LB — Left Back','RWB — Right Wing Back','LWB — Left Wing Back','CDM — Defensive Midfielder','CM — Central Midfielder','CAM — Attacking Midfielder','RM — Right Midfielder','LM — Left Midfielder','RW — Right Wing','LW — Left Wing','ST — Striker','CF — Centre Forward','SS — Second Striker'];
const AR=['Strong football ability','Good attitude','Good team fit','Good pace and fitness','Good technical skills','Previous experience is suitable','Position fits squad needs','Committed to practice sessions','Good communication','Recommended for squad'];
const RR=['Insufficient football experience','Position not currently needed','Poor availability','Does not meet squad requirements','Incomplete player profile','Previous experience not suitable','Fitness level needs improvement','Limited commitment to practices','Squad is currently full','Other / management decision'];
const F={
 '6a':{attacking:{name:'Attacking',slots:[['GK',50,90],['DEF',25,68],['MID',50,50],['ATT',50,18],['ATT',78,28],['ATT',22,28]]},balanced:{name:'Balanced',slots:[['GK',50,90],['DEF',25,68],['MID',50,50],['ATT',50,18],['ATT',78,28],['ATT',22,28]]},defensive:{name:'Defensive',slots:[['GK',50,90],['DEF',25,68],['DEF',75,68],['MID',50,50],['MID',50,30],['ATT',50,15]]}},
 '11a':{attacking:{name:'Attacking',slots:[['GK',50,92],['RB',82,76],['CB',62,76],['LB',18,76],['CB',38,76],['CDM',50,58],['CM',35,44],['CAM',65,40],['RW',82,24],['LW',18,24],['ST',50,12]]},balanced:{name:'Balanced',slots:[['GK',50,92],['RB',82,76],['CB',50,78],['LB',18,76],['CB',38,76],['CDM',50,60],['CM',32,48],['CAM',68,48],['RW',82,28],['LW',18,28],['ST',50,14]]},defensive:{name:'Defensive',slots:[['GK',50,92],['RB',82,76],['CB',62,76],['LB',18,76],['CB',38,76],['CDM',35,58],['CDM',65,58],['CM',50,42],['RM',80,30],['LM',20,30],['ST',50,12]]}}
};
const E={six:{players:[],captain:null,vc:null,subs:[]},eleven:{players:[],captain:null,vc:null,subs:[]}};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const toast=x=>{const t=$('toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
const error=(id,x)=>{$(id).innerHTML='<div class="err">'+esc(x)+'</div>'};
const success=(id,x)=>{$(id).innerHTML='<div class="ok">'+esc(x)+'</div>'};
const getT=async()=>{const x=await getDoc(doc(db,'settings','public'));return x.exists()?x.data():{formations:structuredClone(F),activeFormation:{six:'balanced',eleven:'balanced'},acceptReasons:AR,rejectReasons:RR,bestPlayer:'',totalTeamMembers:0,matchesPlayed:0,matchPlayers6a:6,matchPlayers11a:11,positionLabels:POSLABEL}};
const getS=async()=>{const x=await getDoc(doc(db,'squad','data'));return x.exists()?x.data():structuredClone(E)};
function normalizeSquad(s){
 if(s.six||s.eleven)return {six:{...E.six,...s.six},eleven:{...E.eleven,...s.eleven}};
 if(s['6a']||s['11a'])return {six:{...E.six,...s['6a']},eleven:{...E.eleven,...s['11a']}};
 return structuredClone(E);
}
function playerObj(p){return typeof p==='string'?{name:p,pos:'',number:''}:p||{name:'',pos:'',number:''}}
function squadSideKey(side){return side==='6a'?'six':'eleven'}
function fillPositions(){const all=[...POS6,...POS11.filter(x=>!POS6.includes(x))];$('pos').innerHTML=all.map(x=>`<option value="${x}">${x}</option>`).join('');$('lineupPosition').innerHTML=all.map(x=>`<option value="${x}">${x}</option>`).join('')}
fillPositions();
$('loginBtn').onclick=async()=>{const e=$('user').value.trim(),p=$('pass').value;$('err').textContent='';if(!e||!p){$('err').textContent='Enter email and password.';return}$('loginBtn').disabled=true;$('loginBtn').textContent='SIGNING IN...';try{await signInWithEmailAndPassword(auth,e,p)}catch(x){const m={'auth/invalid-credential':'Incorrect email or password.','auth/wrong-password':'Incorrect password.','auth/user-not-found':'No user found with this email.','auth/invalid-email':'Invalid email.','auth/too-many-requests':'Too many attempts. Try again later.','auth/network-request-failed':'Network error.'};$('err').textContent=m[x.code]||x.message}finally{$('loginBtn').disabled=false;$('loginBtn').textContent='SIGN IN'}};
$('pass').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,u=>{if(u){$('login').style.display='none';$('app').style.display='block';refresh()}else{$('login').style.display='grid';$('app').style.display='none'}});
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelector(`[data-page="${id}"]`)?.classList.add('active');if(id==='lineup')loadLineup();if(id==='squad')loadPlayers()};window.show=show;document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>show(x.dataset.page));
async function getApps(){try{return (await getDocs(query(collection(db,'applications'),orderBy('createdAt','desc')))).docs.map(d=>({id:d.id,...d.data()}))}catch(e){return (await getDocs(collection(db,'applications'))).docs.map(d=>({id:d.id,...d.data()}))}}
function badge(s){return `<span class="badge ${s==='Approved'?'approved':s==='Rejected'?'rejected':'pending'}">${esc(s||'Pending')}</span>`}
async function status(id,st){try{const r=doc(db,'applications',id),x=await getDoc(r);if(!x.exists())return;const a=x.data(),t=await getT(),list=st==='Approved'?(t.acceptReasons||AR):(t.rejectReasons||RR);const v=prompt((st==='Approved'?'Select acceptance reason:\n':'Select decline reason:\n')+list.map((z,i)=>`${i+1}. ${z}`).join('\n')+'\n\nEnter number or custom reason:',a.reason||'');if(v===null)return;const n=parseInt(v),reason=n>=1&&n<=list.length?list[n-1]:v.trim();await updateDoc(r,{status:st,reason,reviewedAt:Date.now()});toast('Application '+st);await refresh()}catch(e){toast('Status update failed: '+e.message)}}window.setStatus=status;
async function apps(){const a=await getApps();$('total').textContent=a.length;$('pending').textContent=a.filter(x=>!['Approved','Rejected'].includes(x.status)).length;$('approved').textContent=a.filter(x=>x.status==='Approved').length;const rows=a.map(x=>`<tr><td>${esc(x.name)}</td><td>@${esc(String(x.instagram||'').replace(/^@/,''))}</td><td>${esc(x.phone)}</td><td>${esc((x.squads||[]).join(' + '))}</td><td>${badge(x.status)}</td><td><button class="btn small" onclick="setStatus('${x.id}','Approved')">✓</button> <button class="btn small" onclick="setStatus('${x.id}','Rejected')">×</button></td></tr>`).join('');$('recent').innerHTML=rows||'<tr><td colspan="6">No applications yet.</td></tr>';$('apps').innerHTML=a.length?a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.age)}</td><td>@${esc(String(x.instagram||'').replace(/^@/,''))}</td><td>${esc(x.phone)}</td><td>${esc(x.playingPosition||'—')}</td><td>${esc(x.jerseySize||'—')} #${esc(x.jerseyNumber||'—')}</td><td>${esc(x.previousTeam||'—')}</td><td>${esc((x.squads||[]).join(' + '))}</td><td>${esc(x.location||'')}</td><td>${badge(x.status)}</td><td><button class="btn small" onclick="viewApp('${x.id}')">VIEW</button> <button class="btn small" onclick="setStatus('${x.id}','Approved')">✓</button> <button class="btn small" onclick="setStatus('${x.id}','Rejected')">×</button></td></tr>`).join(''):'<tr><td colspan="11">No applications yet.</td></tr>'}
window.viewApp=async id=>{const x=await getDoc(doc(db,'applications',id));if(!x.exists())return;const a=x.data();alert(`Application\n\nName: ${a.name||''}\nAge: ${a.age||''}\nPosition: ${a.playingPosition||''}\nJersey: ${a.jerseySize||''} #${a.jerseyNumber||''}\nPrevious team: ${a.previousTeam||''}\nSquad: ${(a.squads||[]).join(' + ')}\nInstagram: ${a.instagram||''}\nPhone: ${a.phone||''}\nLocation: ${a.location||''}\nStatus: ${a.status||''}\nReason: ${a.reason||'—'}`)};
$('search').oninput=async e=>{const q=e.target.value.toLowerCase();const a=(await getApps()).filter(x=>(`${x.name||''} ${x.instagram||''} ${x.phone||''}`).toLowerCase().includes(q));$('apps').innerHTML=a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.age)}</td><td>@${esc(String(x.instagram||'').replace(/^@/,''))}</td><td>${esc(x.phone)}</td><td>${esc(x.playingPosition||'—')}</td><td>${esc(x.jerseySize||'—')} #${esc(x.jerseyNumber||'—')}</td><td>${esc(x.previousTeam||'—')}</td><td>${esc((x.squads||[]).join(' + '))}</td><td>${esc(x.location||'')}</td><td>${badge(x.status)}</td><td><button class="btn small" onclick="viewApp('${x.id}')">VIEW</button></td></tr>`).join('')||'<tr><td colspan="11">No matches.</td></tr>'};
function renderPlayerRow(p,actions=''){p=playerObj(p);return `<div class="player-row"><div><b>${esc(p.name||'Unnamed')} ${p.number!==''?`#${esc(p.number)}`:''}</b><div class="role">${esc(p.pos||'—')} • ${esc(p.roleLabel||'')}</div></div><div class="row">${actions}</div></div>`}
async function loadPlayers(){const s=normalizeSquad(await getS());$('sixList').innerHTML=(s.six.players||[]).map(p=>renderPlayerRow(p,`<button class="btn small" onclick="editMaster('${esc(playerObj(p).name)}','6a')">EDIT</button>`)).join('')||'<div class="empty">No 6A team members.</div>';$('elevenList').innerHTML=(s.eleven.players||[]).map(p=>renderPlayerRow(p,`<button class="btn small" onclick="editMaster('${esc(playerObj(p).name)}','11a')">EDIT</button>`)).join('')||'<div class="empty">No 11A team members.</div>';await loadLineupSelects(s)}
window.editMaster=(name,side)=>{const s=normalizeSquad(window.__squad||{});const arr=s[squadSideKey(side)].players||[];const p=arr.map(playerObj).find(x=>x.name===name);if(!p)return;$('editId').value=name;$('pname').value=p.name;$('pnumber').value=p.number??'';$('team').value=side;$('pos').value=p.pos||'GK';$('role').value=p.role||'field';$('starting').value=String(p.starting??true);window.scrollTo({top:0,behavior:'smooth'})};
$('clearPlayer').onclick=()=>{['editId','pname','pnumber'].forEach(id=>$(id).value='');$('team').value='6a';$('pos').value='GK';$('role').value='field';$('starting').value='true'};
$('savePlayer').onclick=async()=>{const name=$('pname').value.trim(),num=$('pnumber').value.trim(),side=$('team').value;if(!name||num===''){toast('Player name and jersey number required');return}try{let s=normalizeSquad(await getS());const key=side==='6a'?'six':side==='11a'?'eleven':null;const data={name,number:Number(num),pos:$('pos').value,role:$('role').value,starting:$('starting').value==='true'};if(key){let arr=(s[key].players||[]).map(playerObj);const old=$('editId').value;const idx=old?arr.findIndex(p=>p.name===old):arr.findIndex(p=>p.name===name);if(idx>=0)arr[idx]=data;else arr.push(data);s[key].players=arr}else{for(const k of ['six','eleven']){let arr=(s[k].players||[]).map(playerObj);const idx=arr.findIndex(p=>p.name===name);if(idx<0)arr.push(data);else arr[idx]=data;s[k].players=arr}}await setDoc(doc(db,'squad','data'),s);window.__squad=s;$('clearPlayer').click();toast('Team member saved');await loadPlayers();await loadLineup()}catch(e){toast('Save failed: '+e.message)}};
async function loadLineupSelects(s){const all=[...new Map([...s.six.players,...s.eleven.players].map(p=>{p=playerObj(p);return[p.name,p]})).values()];$('lineupPlayer').innerHTML=all.map(p=>`<option value="${esc(p.name)}">${esc(p.name)} #${esc(p.number??'')}</option>`).join('');if(!all.length)$('lineupPlayer').innerHTML='<option value="">No saved players</option>'}
$('lineupSide').onchange=async()=>{const s=normalizeSquad(await getS());const side=s[squadSideKey($('lineupSide').value)];const p=(side.players||[]).map(playerObj).find(x=>x.name===$('lineupPlayer').value);$('lineupPosition').value=p?.pos||'GK'};
$('lineupPlayer').onchange=async()=>{const s=normalizeSquad(await getS());for(const k of ['six','eleven']){const p=(s[k].players||[]).map(playerObj).find(x=>x.name===$('lineupPlayer').value);if(p){$('lineupSide').value=k==='six'?'6a':'11a';$('lineupPosition').value=p.pos||'GK';break}}};
$('saveLineup').onclick=async()=>{const name=$('lineupPlayer').value;if(!name){toast('Select a saved player');return}try{let s=normalizeSquad(await getS()),k=squadSideKey($('lineupSide').value),side=s[k];side.players=(side.players||[]).map(playerObj);let p=side.players.find(x=>x.name===name);if(!p){toast('Player is not in this side. Save the player to this side first.');return}p.pos=$('lineupPosition').value;p.role=$('lineupRole').value;p.starting=$('lineupRole').value==='field'||$('lineupRole').value==='captain'||$('lineupRole').value==='vc';side.players=side.players.filter(x=>x.name!==name);side.subs=(side.subs||[]).map(playerObj).filter(x=>x.name!==name);if($('lineupRole').value==='captain'){if(side.captain&&playerObj(side.captain).name!==name){const old=playerObj(side.captain);old.role='field';side.players.push(old)}side.captain=p}else if($('lineupRole').value==='vc'){if(side.vc&&playerObj(side.vc).name!==name){const old=playerObj(side.vc);old.role='field';side.players.push(old)}side.vc=p}else if($('lineupRole').value==='sub'){side.subs.push({...p,role:'sub',starting:false})}else{side.players.push({...p,role:'field',starting:true})}await setDoc(doc(db,'squad','data'),s);window.__squad=s;toast('Assignment saved');await loadPlayers();await loadLineup()}catch(e){toast('Assignment failed: '+e.message)}};
$('refreshLineup').onclick=()=>loadLineup();
function lineCard(p,label){p=playerObj(p);return `<div class="player-row"><div><b>${esc(p.name||'Unnamed')}</b><div class="role">${esc(p.pos||'—')} • ${esc(label)}</div></div></div>`}
async function loadLineup(){const s=normalizeSquad(await getS());window.__squad=s;for(const [key,prefix] of [['six','six'],['eleven','eleven']]){const side=s[key]||E[key];const c=side.captain?playerObj(side.captain):null,v=side.vc?playerObj(side.vc):null;$(`${prefix}Captain`).innerHTML=c?lineCard(c,'CAPTAIN'):'<div class="empty">Not assigned</div>';$(`${prefix}Vc`).innerHTML=v?lineCard(v,'VICE CAPTAIN'):'<div class="empty">Not assigned</div>';$(`${prefix}Starting`).innerHTML=(side.players||[]).map(p=>lineCard(p,'STARTING')).join('')||'<div class="empty">No starting players.</div>';$(`${prefix}Subs`).innerHTML=(side.subs||[]).map(p=>lineCard(p,'SUBSTITUTE')).join('')||'<div class="empty">No substitutes.</div>'}await loadLineupSelects(s)}
function parseSlots(name,text){const slots=text.split(/\n/).map(x=>x.trim()).filter(Boolean).map(x=>{const [p,l,t]=x.split(',').map(v=>v.trim());return[p||'PLAYER',Math.max(0,Math.min(100,Number(l)||0)),Math.max(0,Math.min(100,Number(t)||0))]});return slots.length?{name:name.trim()||'Custom',slots}:null}
async function loadFormations(){const s=await getT(),af=s.activeFormation||{six:'balanced',eleven:'balanced'},f=s.formations||structuredClone(F);$('active6a').value=af.six||af['6a']||'balanced';$('active11a').value=af.eleven||af['11a']||'balanced';const a=f.six||f['6a']||F['6a'],b=f.eleven||f['11a']||F['11a'];const fa=a[$('active6a').value]||a.custom||F['6a'].balanced,fb=b[$('active11a').value]||b.custom||F['11a'].balanced;$('f6name').value=fa.name;$('f6slots').value=(fa.slots||[]).map(x=>Array.isArray(x)?x.join(','):String(x)).join('\n');$('f11name').value=fb.name;$('f11slots').value=(fb.slots||[]).map(x=>Array.isArray(x)?x.join(','):String(x)).join('\n')}
$('saveActive').onclick=async()=>{try{await setDoc(doc(db,'settings','public'),{activeFormation:{six:$('active6a').value,eleven:$('active11a').value}},{merge:true});toast('Active formations saved');await loadFormations()}catch(e){toast('Formation save failed: '+e.message)}};
async function saveCustom(side,name,text){const f=parseSlots(name,text);if(!f){toast('Add formation slots');return}const slots=(f.slots||[]).map(x=>x.join(','));const patch={};patch['formations.'+side+'.custom']={name:f.name,slots};try{await setDoc(doc(db,'settings','public'),patch,{merge:true});toast('Custom '+side.toUpperCase()+' formation saved');await loadFormations()}catch(e){toast('Custom formation save failed: '+e.message)}}
$('saveF6').onclick=()=>saveCustom('six',$('f6name').value,$('f6slots').value);$('saveF11').onclick=()=>saveCustom('eleven',$('f11name').value,$('f11slots').value);
async function loadSettings(){const s=await getT();$('totalTeamMembers').value=s.totalTeamMembers??0;$('matchesPlayed').value=s.matchesPlayed??s.matchPlayed??0;$('mvp').value=s.bestPlayer||s.mvp||'';$('matchPlayers6a').value=s.matchPlayers6a??6;$('matchPlayers11a').value=s.matchPlayers11a??11;$('positionLabels').value=(s.positionLabels||POSLABEL).join('\n');$('acceptReasons').value=(s.acceptReasons||AR).join('\n');$('rejectReasons').value=(s.rejectReasons||RR).join('\n');$('dashMembers').textContent=s.totalTeamMembers??0;$('dashMatches').textContent=s.matchesPlayed??s.matchPlayed??0;$('dashMvp').textContent=s.bestPlayer||s.mvp||'—'}
$('saveSettings').onclick=async()=>{try{const patch={totalTeamMembers:Math.max(0,Number($('totalTeamMembers').value)||0),matchesPlayed:Math.max(0,Number($('matchesPlayed').value)||0),bestPlayer:$('mvp').value.trim(),matchPlayers6a:Math.max(1,Number($('matchPlayers6a').value)||6),matchPlayers11a:Math.max(1,Number($('matchPlayers11a').value)||11),positionLabels:$('positionLabels').value.split(/\n/).map(x=>x.trim()).filter(Boolean),acceptReasons:$('acceptReasons').value.split(/\n/).map(x=>x.trim()).filter(Boolean),rejectReasons:$('rejectReasons').value.split(/\n/).map(x=>x.trim()).filter(Boolean)};await setDoc(doc(db,'settings','public'),patch,{merge:true});success('settingsMsg','Team settings saved successfully.');await loadSettings()}catch(e){error('settingsMsg',e.message)}};
async function refresh(){await apps();await loadSettings();await loadPlayers();await loadLineup();await loadFormations()}